# Generated by Django 6.0.4 on 2026-04-11 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_usage_kwh', models.FloatField(blank=True, null=True)),
                ('water_usage_liters', models.FloatField(blank=True, null=True)),
                ('clothing_spend', models.FloatField(blank=True, null=True)),
                ('consumption_spend', models.FloatField(blank=True, null=True)),
                ('housing_type', models.CharField(default='Dormitory', max_length=50)),
                ('transport_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('electricity_kwh_daily', models.FloatField(blank=True, null=True)),
                ('transport_km', models.FloatField(blank=True, null=True)),
                ('food_type', models.CharField(blank=True, max_length=50, null=True)),
                ('waste_kg', models.FloatField(blank=True, null=True)),
                ('predicted_co2', models.FloatField()),
                ('carbon_level', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='General', max_length=100)),
                ('role', models.CharField(default='user', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
